// QD1_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module QD1_mm_interconnect_1 (
		input  wire        the_altpll_c0_clk,                                     //                                   the_altpll_c0.clk
		input  wire        the_onchip_memory2_reset1_reset_bridge_in_reset_reset, // the_onchip_memory2_reset1_reset_bridge_in_reset.reset
		input  wire        the_vectorblox_orca_reset_reset_bridge_in_reset_reset, // the_vectorblox_orca_reset_reset_bridge_in_reset.reset
		input  wire [31:0] the_vectorblox_orca_instruction_address,               //                 the_vectorblox_orca_instruction.address
		output wire        the_vectorblox_orca_instruction_waitrequest,           //                                                .waitrequest
		input  wire        the_vectorblox_orca_instruction_read,                  //                                                .read
		output wire [31:0] the_vectorblox_orca_instruction_readdata,              //                                                .readdata
		output wire        the_vectorblox_orca_instruction_readdatavalid,         //                                                .readdatavalid
		output wire [12:0] the_onchip_memory2_s1_address,                         //                           the_onchip_memory2_s1.address
		output wire        the_onchip_memory2_s1_write,                           //                                                .write
		input  wire [31:0] the_onchip_memory2_s1_readdata,                        //                                                .readdata
		output wire [31:0] the_onchip_memory2_s1_writedata,                       //                                                .writedata
		output wire [3:0]  the_onchip_memory2_s1_byteenable,                      //                                                .byteenable
		output wire        the_onchip_memory2_s1_chipselect,                      //                                                .chipselect
		output wire        the_onchip_memory2_s1_clken                            //                                                .clken
	);

	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_waitrequest;   // the_onchip_memory2_s1_translator:uav_waitrequest -> the_vectorblox_orca_instruction_translator:uav_waitrequest
	wire  [31:0] the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdata;      // the_onchip_memory2_s1_translator:uav_readdata -> the_vectorblox_orca_instruction_translator:uav_readdata
	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_debugaccess;   // the_vectorblox_orca_instruction_translator:uav_debugaccess -> the_onchip_memory2_s1_translator:uav_debugaccess
	wire  [31:0] the_vectorblox_orca_instruction_translator_avalon_universal_master_0_address;       // the_vectorblox_orca_instruction_translator:uav_address -> the_onchip_memory2_s1_translator:uav_address
	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_read;          // the_vectorblox_orca_instruction_translator:uav_read -> the_onchip_memory2_s1_translator:uav_read
	wire   [3:0] the_vectorblox_orca_instruction_translator_avalon_universal_master_0_byteenable;    // the_vectorblox_orca_instruction_translator:uav_byteenable -> the_onchip_memory2_s1_translator:uav_byteenable
	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdatavalid; // the_onchip_memory2_s1_translator:uav_readdatavalid -> the_vectorblox_orca_instruction_translator:uav_readdatavalid
	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_lock;          // the_vectorblox_orca_instruction_translator:uav_lock -> the_onchip_memory2_s1_translator:uav_lock
	wire         the_vectorblox_orca_instruction_translator_avalon_universal_master_0_write;         // the_vectorblox_orca_instruction_translator:uav_write -> the_onchip_memory2_s1_translator:uav_write
	wire  [31:0] the_vectorblox_orca_instruction_translator_avalon_universal_master_0_writedata;     // the_vectorblox_orca_instruction_translator:uav_writedata -> the_onchip_memory2_s1_translator:uav_writedata
	wire   [2:0] the_vectorblox_orca_instruction_translator_avalon_universal_master_0_burstcount;    // the_vectorblox_orca_instruction_translator:uav_burstcount -> the_onchip_memory2_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) the_vectorblox_orca_instruction_translator (
		.clk                    (the_altpll_c0_clk),                                                                  //                       clk.clk
		.reset                  (the_vectorblox_orca_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (the_vectorblox_orca_instruction_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (the_vectorblox_orca_instruction_waitrequest),                                        //                          .waitrequest
		.av_read                (the_vectorblox_orca_instruction_read),                                               //                          .read
		.av_readdata            (the_vectorblox_orca_instruction_readdata),                                           //                          .readdata
		.av_readdatavalid       (the_vectorblox_orca_instruction_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                               //               (terminated)
		.av_byteenable          (4'b1111),                                                                            //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                                               //               (terminated)
		.av_write               (1'b0),                                                                               //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                               //               (terminated)
		.av_lock                (1'b0),                                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                                               //               (terminated)
		.uav_clken              (),                                                                                   //               (terminated)
		.av_clken               (1'b1),                                                                               //               (terminated)
		.uav_response           (2'b00),                                                                              //               (terminated)
		.av_response            (),                                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (13),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) the_onchip_memory2_s1_translator (
		.clk                    (the_altpll_c0_clk),                                                                  //                      clk.clk
		.reset                  (the_onchip_memory2_reset1_reset_bridge_in_reset_reset),                              //                    reset.reset
		.uav_address            (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (the_vectorblox_orca_instruction_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (the_onchip_memory2_s1_address),                                                      //      avalon_anti_slave_0.address
		.av_write               (the_onchip_memory2_s1_write),                                                        //                         .write
		.av_readdata            (the_onchip_memory2_s1_readdata),                                                     //                         .readdata
		.av_writedata           (the_onchip_memory2_s1_writedata),                                                    //                         .writedata
		.av_byteenable          (the_onchip_memory2_s1_byteenable),                                                   //                         .byteenable
		.av_chipselect          (the_onchip_memory2_s1_chipselect),                                                   //                         .chipselect
		.av_clken               (the_onchip_memory2_s1_clken),                                                        //                         .clken
		.av_read                (),                                                                                   //              (terminated)
		.av_begintransfer       (),                                                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                                                   //              (terminated)
		.av_burstcount          (),                                                                                   //              (terminated)
		.av_readdatavalid       (1'b0),                                                                               //              (terminated)
		.av_waitrequest         (1'b0),                                                                               //              (terminated)
		.av_writebyteenable     (),                                                                                   //              (terminated)
		.av_lock                (),                                                                                   //              (terminated)
		.uav_clken              (1'b0),                                                                               //              (terminated)
		.av_debugaccess         (),                                                                                   //              (terminated)
		.av_outputenable        (),                                                                                   //              (terminated)
		.uav_response           (),                                                                                   //              (terminated)
		.av_response            (2'b00),                                                                              //              (terminated)
		.uav_writeresponsevalid (),                                                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                //              (terminated)
	);

endmodule
